### PR TITLE
Hello world

### PR DESCRIPTION
**Pull request by ketanmalik**
This merge request adds a `src` folder and two files - `App.js` and `index.html`. This just prints `Hello World` using React.

### CODE REVIEW

**Review by pandeymeenakshi — COMMENTED** [review]
Hello world using only Js ?

**Comment by SumitARG** [comment]
You can add a few code comments wherever possible

**Comment by ketanmalik** [comment]
> You can add a few code comments wherever possible

While I agree commenting is an essential part to writing clean codes, I just believe it is an overkill for this level of coding.
I'll surely be adding relevant comments as things get complex.

**Comment by ketanmalik** [comment]
> Hello world using only Js ?

I actually only added the file using React but there are commits where I tried all 3 approaches. I'll add a file for only JS before merging.

**Pull request merged**
